### ISSUE TITLE
sign up: error when the user tries to create a new account

### ISSUE THREAD

**Issue by drjova** [inveniosoftware-attic/invenio-app-demomarc21#28]
Way to reproduce, click signup to app-ilis, fill the form up and click the "Sign up" button

```
Traceback (most recent call last):
  File "/Users/user/.virtualenvs/invenio-first-week/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/user/.virtualenvs/invenio-first-week/lib/python2.7/site-packages/werkzeug/wsgi.py", line 660, in __call__
    return app(environ, start_response)
  File "/Users/user/.virtualenvs/invenio-first-week/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/user/.virtualenvs/invenio-first-week/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/user/.virtualenvs/invenio-first-week/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/user/.virtualenvs/invenio-first-week/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/user/.virtualenvs/invenio-first-week/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/user/.virtualenvs/invenio-first-week/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/user/.virtualenvs/invenio-first-week/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/user/.virtualenvs/invenio-first-week/lib/python2.7/site-packages/flask_security/decorators.py", line 230, in wrapper
    return f(*args, **kwargs)
  File "/Users/user/.virtualenvs/invenio-first-week/lib/python2.7/site-packages/flask_security/views.py", line 118, in register
    user = register_user(**form.to_dict())
  File "/Users/user/.virtualenvs/invenio-first-week/lib/python2.7/site-packages/flask_security/registerable.py", line 41, in register_user
    'welcome', user=user, confirmation_link=confirmation_link)
  File "/Users/user/.virtualenvs/invenio-first-week/lib/python2.7/site-packages/flask_security/utils.py", line 401, in send_mail
    mail.send(msg)
  File "/Users/user/.virtualenvs/invenio-first-week/lib/python2.7/site-packages/flask_mail.py", line 492, in send
    message.send(connection)
  File "/Users/user/.virtualenvs/invenio-first-week/lib/python2.7/site-packages/flask_mail.py", line 427, in send
    connection.send(self)
  File "/Users/user/.virtualenvs/invenio-first-week/lib/python2.7/site-packages/flask_mail.py", line 194, in send
    email_dispatched.send(message, app=current_app._get_current_object())
  File "/Users/user/.virtualenvs/invenio-first-week/lib/python2.7/site-packages/blinker/base.py", line 267, in send
    for receiver in self.receivers_for(sender)]
  File "/Users/user/.virtualenvs/invenio-first-week/src/invenio-mail/invenio_mail/ext.py", line 47, in print_email
    '{0}\n{1}\n'.format(message.as_string(), '-' * 79))
  File "/Users/user/.virtualenvs/invenio-first-week/lib/python2.7/site-packages/flask_mail.py", line 381, in as_string
    return self._message().as_string()
  File "/Users/user/.virtualenvs/invenio-first-week/lib/python2.7/site-packages/flask_mail.py", line 330, in _message
    msg['From'] = sanitize_address(self.sender, encoding)
  File "/Users/user/.virtualenvs/invenio-first-week/lib/python2.7/site-packages/flask_mail.py", line 105, in sanitize_address
    nm, addr = addr
ValueError: too many values to unpack

```

**Comment by switowski** [comment]
This is an issue with the `flask-security` using `LocalProxy` as the sender (https://github.com/mattupstate/flask-security/issues/685) that causes `flask-mail` to fail (https://github.com/mattupstate/flask-mail/issues/148). I'm trying to find a way to fix it without monkey-patching any of those packages.

**Comment by lnielsen** [comment]
You can probably hard-code the [``SECURITY_EMAIL_SENDER``](https://github.com/mattupstate/flask-security/blob/develop/flask_security/core.py#L87-L89) which makes sure it is not a LocalProxy.

**Comment by switowski** [comment]
@lnielsen hmm, so basically reverting this commit: https://github.com/mattupstate/flask-security/commit/a0eba4b77b367a385a8bbf83afcf784295bd6467 ?
